name = "discord-interactions-worker"
main = "worker.js"
compatibility_date = "2023-10-02"

[vars]
DISCORD_PUBLIC_KEY = "TODO_REPLACE_WITH_PUBLIC_KEY"
DISCORD_APPLICATION_ID = "TODO_REPLACE_WITH_APPLICATION_ID"
DISCORD_CLIENT_SECRET = "TODO_REPLACE_WITH_CLIENT_SECRET"
DEV_GUILD_ID = "TODO_REPLACE_WITH_DEV_GUILD_ID"

[[kv_namespaces]]
binding = "MY_KV"
id = "TODO_REPLACE_WITH_NAMESPACE_ID"
